- mindbox/CHANGELOG.md
- mindbox/pubspec.yaml
- mindbox_ios/CHANGELOG.md
- mindbox_ios/ios/Classes/SwiftMindboxIosPlugin.swift
- mindbox_ios/ios/mindbox_ios.podspec
- mindbox_ios/pubspec.yaml
- mindbox_platform_interface/CHANGELOG.md
- mindbox_platform_interface/lib/src/mindbox_platform.dart
- mindbox_platform_interface/lib/src/types/mindbox_method_handler.dart
- mindbox_platform_interface/pubspec.yaml
- mindbox_platform_interface/test/src/types/mindbox_method_handler_test.dart
> Add old format push support

- mindbox/pubspec.yaml
- mindbox_android/android/build.gradle
- mindbox_android/android/src/main/kotlin/cloud/mindbox/mindbox_android/MindboxAndroidPlugin.kt
- mindbox_android/pubspec.yaml
- mindbox_ios/pubspec.yaml
- mindbox_platform_interface/lib/src/mindbox_platform.dart
- mindbox_platform_interface/pubspec.yaml
Issue: https://github.com/mindbox-moscow/issues-mobile-sdk/issues/238
- Add Huawei Push Kit support.
> 238 add huawei support

- mindbox/CHANGELOG.md
- mindbox/README.md
- mindbox/example/lib/main.dart
- mindbox/lib/mindbox.dart
- mindbox/pubspec.yaml
- mindbox/test/mindbox_test.dart
- mindbox_android/CHANGELOG.md
- mindbox_android/README.md
- mindbox_android/android/build.gradle
- mindbox_android/android/src/main/kotlin/cloud/mindbox/mindbox_android/MindboxAndroidPlugin.kt
- mindbox_android/example/android/app/build.gradle
- mindbox_android/example/android/build.gradle
- mindbox_android/example/lib/main.dart
- mindbox_android/lib/src/mindbox_android_platform.dart
- mindbox_android/pubspec.yaml
- mindbox_android/test/mindbox_android_test.dart
- mindbox_ios/CHANGELOG.md
- mindbox_ios/README.md
- mindbox_ios/example/lib/main.dart
- mindbox_ios/ios/Classes/SwiftMindboxIosPlugin.swift
- mindbox_ios/ios/mindbox_ios.podspec
- mindbox_ios/lib/src/mindbox_ios_platform.dart
- mindbox_ios/pubspec.yaml
- mindbox_ios/test/mindbox_ios_test.dart
- mindbox_platform_interface/CHANGELOG.md
- mindbox_platform_interface/lib/src/mindbox_platform.dart
- mindbox_platform_interface/lib/src/types/mindbox_method_handler.dart
- mindbox_platform_interface/pubspec.yaml
- mindbox_platform_interface/test/mindbox_platform_interface_test.dart
- mindbox_platform_interface/test/src/types/mindbox_method_handler_test.dart
Issue: https://github.com/mindbox-moscow/issues-mobile-sdk/issues/253
- Add payload parameter to onPushClickReceived method
> 253 add payload to push received

- mindbox/CHANGELOG.md
- mindbox/lib/mindbox.dart
- mindbox/pubspec.yaml
- mindbox_android/CHANGELOG.md
- mindbox_android/android/build.gradle
- mindbox_android/lib/src/mindbox_android_platform.dart
- mindbox_android/pubspec.yaml
- mindbox_ios/CHANGELOG.md
- mindbox_ios/ios/Classes/SwiftMindboxIosPlugin.swift
- mindbox_ios/ios/mindbox_ios.podspec
- mindbox_ios/lib/src/mindbox_ios_platform.dart
- mindbox_ios/pubspec.yaml
- mindbox_platform_interface/CHANGELOG.md
- mindbox_platform_interface/lib/src/types/mindbox_method_handler.dart
- mindbox_platform_interface/pubspec.yaml
Ticket: https://github.com/mindbox-moscow/issues-mobile-sdk/issues/246
Changes:
* Upgrade iOS SDK dependency to v.2.1.0.
* Upgrade Android SDK dependency to v2.1.3.
* Update init method: you can change sdk configuration without reinstallation of app.
> 246 add reinitialization

- mindbox/pubspec.yaml
- mindbox_android/pubspec.yaml
- mindbox_ios/pubspec.yaml
* Upgrade Android SDK dependency to v2.1.5.
* Upgrade HMS upgraded to 6.5.0.300.
* Fix bug on Android after reinitialization (changing your domain, endpoint and shouldCreateCustomer parameters in existing SDK integration).
> Release 2.1.2

- mindbox/CHANGELOG.md
- mindbox/pubspec.yaml
- mindbox_ios/CHANGELOG.md
- mindbox_ios/ios/mindbox_ios.podspec
- mindbox_ios/pubspec.yaml
* Upgrade iOS Mindbox SDK dependency to v2.1.2.
* Minor iOS changes on to the CodingKey value for the customAction variable in the OperationBodyRequest class.
> Release 2.1.3

- mindbox/CHANGELOG.md
- mindbox/pubspec.yaml
- mindbox_android/CHANGELOG.md
- mindbox_android/android/build.gradle
- mindbox_android/pubspec.yaml
Ticket: https://github.com/mindbox-moscow/issues-mobile-sdk/issues/278
Changes:
- Upgrade Android SDK dependency to v2.1.6
> Upgrade Android SDK dependency to v2.1.6, update change log

- mindbox/CHANGELOG.md
- mindbox/pubspec.yaml
- mindbox_android/CHANGELOG.md
- mindbox_android/android/build.gradle
- mindbox_android/pubspec.yaml
> upgrade Android dependency to 2.1.10

- .github/workflows/analyze_and_test.yml
- .github/workflows/publish.yml
- mindbox/pubspec.yaml
- mindbox/test/mindbox_test.dart
- mindbox_android/test/mindbox_android_test.dart
- mindbox_ios/test/mindbox_ios_test.dart
- mindbox_platform_interface/test/src/types/mindbox_method_handler_test.dart
https://github.com/mindbox-cloud/issues-web-mobile/issues/2691
> Fix deprecated method issue

- mindbox_android/test/mindbox_android_test.dart
https://github.com/mindbox-cloud/issues-web-mobile/issues/2942
> added registerInAppCallbacks test also like in iOS

- .github/workflows/publish.yml
- README.md
- version-update.sh
https://github.com/mindbox-cloud/issues-web-mobile/issues/3120
> MBX-3120: Updating README.md

- mindbox_platform_interface/lib/src/types/configuration.dart
https://github.com/mindbox-cloud/issues-web-mobile/issues/3444
> MBX-3444: make field subscribeCustomerIfCreated optional

- mindbox/lib/mindbox.dart
- mindbox_android/android/src/main/kotlin/cloud/mindbox/mindbox_android/MindboxAndroidPlugin.kt
- mindbox_android/lib/src/mindbox_android_platform.dart
- mindbox_ios/ios/Classes/SwiftMindboxIosPlugin.swift
- mindbox_ios/lib/src/mindbox_ios_platform.dart
- mindbox_platform_interface/lib/src/mindbox_platform.dart
- mindbox_platform_interface/lib/src/types/mindbox_method_handler.dart
https://github.com/mindbox-cloud/issues-web-mobile/issues/3547
> MBX-3547: add logging

- .github/workflows/trigger-build-app.yml
[[Flutter] Настроить автосборки при мерже ветки в develop](https://github.com/mindbox-cloud/issues-web-mobile/issues/3072)
> MBX-3072 Added trigger script

- .github/workflows/trigger-build-app.yml
[[Flutter] Настроить автосборки при мерже ветки в develop](https://github.com/mindbox-cloud/issues-web-mobile/issues/3072)
> MBX-3072 Not on self-hosted

- to-local-dependensies.sh
[[Flutter] Создание локальных сборок на устройстве.](https://github.com/mindbox-cloud/issues-web-mobile/issues/3552)
> MBX-3552 Local updates

- mindbox_ios/ios/mindbox_ios.podspec
[iOS] Поднять минимальную версию iOS с 10.0 до 12.0[#3568](https://github.com/mindbox-cloud/issues-web-mobile/issues/3568)
> MBX-3568: Up podspec version

- .github/workflows/trigger-build-app.yml
[[Mobile] Привести версии пушков к версии SDK](https://github.com/mindbox-cloud/issues-web-mobile/issues/3617)
> MBX-3617 Remove unused param

- example/flutter_example/android/app/src/main/kotlin/cloud/mindbox/flutter_example/MindboxHuaweiMessagingService.kt
https://github.com/mindbox-cloud/issues-web-mobile/issues/3675
> MBX-3675: run handleRemoteMessage asynchronously in example

- mindbox_android/android/build.gradle
- mindbox_android/android/gradle/wrapper/gradle-wrapper.properties
https://tracker.yandex.ru/WMRUSTORE-7
> WMSDK-377: bump gradle, kotlin abd targetSdkVersion

- mindbox_android/android/build.gradle
https://tracker.yandex.ru/WMSDK-391
> WMSDK-391: bump minSdk version

- example/flutter_example/analysis_options.yaml
- example/flutter_example/pubspec.lock
- example/flutter_example/pubspec.yaml
https://tracker.yandex.ru/WMSDK-423
> WMSDK-423: bump shared_preference_android package  in example

- example/flutter_example/lib/view_model/view_model.dart
https://tracker.yandex.ru/WMSDK-429
> WMSDK-429: change notification request

- mindbox/CHANGELOG.md
- mindbox/pubspec.yaml
- mindbox_android/CHANGELOG.md
- mindbox_android/android/build.gradle
- mindbox_android/pubspec.yaml
- mindbox_ios/CHANGELOG.md
- mindbox_ios/ios/mindbox_ios.podspec
- mindbox_ios/pubspec.yaml
- mindbox_platform_interface/CHANGELOG.md
- mindbox_platform_interface/pubspec.yaml
[WMSDK-434](https://tracker.yandex.ru/WMSDK-434)
> Bump SDK version to 2.13.2-rc

- .github/workflows/analyze_and_test.yml
- .github/workflows/publish-manual.yml
- .github/workflows/publish-master.yml
- .github/workflows/publish-rc-mission.yml
- .github/workflows/publish-reusable.yml
- .github/workflows/release-version-check.yml
- .github/workflows/trigger-build-app-develop.yml
- .github/workflows/trigger-build-app-manual.yml
- .github/workflows/trigger-build-app-master-support.yml
- .github/workflows/trigger-build-app-reusable.yml
https://tracker.yandex.ru/WMSDK-443
> WMSDK-443: change publish flow
